- name: create instance(s)
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    master: datalyse-master
    slaves:
      - datalyse-1
      - datalyse-2
      - datalyse-3
      - datalyse-4
      # - datalyse-5
      # - datalyse-6
    machine_type: n1-standard-1
    image: ubuntu-1404-trusty
    zone: europe-west1-b
    gce_credentials: &gce_credentials
      service_account_email: 477431100958-5qk956khmhrvo47skol33enm1hbe6q07@developer.gserviceaccount.com
      pem_file: keys/datalyse-exp.pem
      project_id: datalyse-exp

  tasks:
    - name: launch master instance
      gce:
        instance_names: "{{ master }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        <<: *gce_credentials
        tags:
          - docker
          - master
      register: gce_master

    - name: launch slaves instances
      gce:
        instance_names: "{{ slaves|join(',') }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        <<: *gce_credentials
        tags:
          - docker
          - slave
      register: gce_slaves

    - name: expose docker port 8080 for ambari web console
      gce_net:
        name: default  
        fwname: allow-ambari-web-console
        src_range: 0.0.0.0/0
        allowed: tcp:8080
        <<: *gce_credentials
        # TODO: target_tags (available from ansible 1.9)
        # target_tags:
        #   - master

    - name: wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}" 
        port: 22
        delay: 10
        timeout: 60 
        state: started
      with_items: gce_master.instance_data + gce_slaves.instance_data
