- name: stop all ambari agents
  hosts: 
    - tag_slave
    - tag_master
  tasks:

  - name: stop ambari agent
    docker: 
      name: ambari-agent
      # FIXME: why do I need image for absent??
      image: datalyse-master:5000/datalyse/ambari-agent
      state: absent

- name: stop all ambari servers
  hosts: tag_master
  tasks:

  - name: stop ambari server
    docker: 
      name: ambari-server
      # FIXME: why do I need image for absent??
      image: datalyse-master:5000/datalyse/ambari-server
      state: absent
