# - name: install python requirements
#   pip: name={{ item }}
#   sudo: yes
#   with_items:
#     - requests
#     - python-ambariclient

- name: create a blueprint directory
  file: path={{ blueprints_dir }} state=directory

- name: copy blueprint
  template: src={{ item }}.j2 dest={{ blueprints_dir }}/{{ item }}
  with_items: blueprints
