HOSTNAME = "boot2openstack"
MEMORY = 1024*8
CPUS = 4
IP = "192.168.59.103"

# ------------------------------------------------------------------------------

VAGRANTFILE_API_VERSION = "2" 

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config| 
  
  config.vm.box = "ubuntu/trusty64" 

  config.vm.hostname = HOSTNAME

  # eth0: NAT network - is created by default by Vagrant
  # eth1: host-only network - to access the VM using its IP address
  config.vm.network :private_network, ip: IP

  config.vm.provider :virtualbox do |vb|
    vb.name = HOSTNAME
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

end
