- name: start ambari agent
  docker:
    # TODO: externalize using hostvars['tag_master'][...]
    image: datalyse-master:5000/datalyse/ambari-agent
    insecure_registry: yes
    registry: datalyse-master:5000
    name: ambari-agent
    hostname: "{{ weave_ambari_agent_hostname }}"
    domainname: "{{ weave_domain }}"

    # FIXME: this is bad, but from whatever reason on google compute cloud
    # a root process cannot read /proc/<pid>/exe of a process it spawned
    # likely due to https://github.com/docker/docker/issues/6607
    # I tried adding the SYS_PTRACE cap, but it remains the same
    # on a vbox it works
    privileged: yes
    dns: "{{ docker_dns }}"
    dns_search: "{{ weave_domain }}"
    env:
      # TODO: externalize
      AMBARI_SERVER: ambari-server.weave.local
    state: running

# https://github.com/docker/docker/issues/4036
- name: sleep because of docker bug #4036
  command: sleep 1

- name: attach ambari agent to weave network
  command: "{{ weave_bin }} attach {{ weave_ambari_agent_cidr }} ambari-agent"