- name: start ambari server
  docker:
    image: datalyse-master:5000/datalyse/ambari-server
    name: ambari-server
    hostname: "{{ weave_ambari_server_hostname }}"
    domainname: "{{ weave_domain }}"
    ports: 8080:8080

    # FIXME: this is bad, but from whatever reason on google compute cloud
    # a root process cannot read /proc/<pid>/exe of a process it spawned
    # likely due to https://github.com/docker/docker/issues/6607
    # I tried adding the SYS_PTRACE cap, but it remains the same
    # on a vbox it works
    privileged: yes
    dns: "{{ docker_dns }}" 
    dns_search: "{{ weave_domain }}"
    state: running

# https://github.com/docker/docker/issues/4036
- name: sleep because of docker bug #4036
  command: sleep 1

- name: attach ambari server to weave network
  command: "{{ weave_bin }} attach {{ weave_ambari_server_cidr }} ambari-server"