- name: basic configuration
  hosts: all
  vars:
    - admin_username: admin
    - admin_password: stack

    - fixed_range: 10.1.1.0/24

    - keystone_host: "{{ ansible_env.KEYSTONE_KEYSTONE_MASTER_HOST }}"
    - keystone_endpoint: "http://{{ keystone_host }}:35357/v2.0"
    - keystone_password: "{{ ansible_env.KEYSTONE_PASSWORD }}"

    - glance_host: "{{ ansible_env.GLANCE_GLANCE_MASTER_HOST }}"
    - nova_controller_host: "{{ ansible_env.NOVA_CONTROLLER_NOVA_CONTROLLER_MASTER_HOST }}"

    - openrc:
        OS_USERNAME: "{{ admin_username }}"
        OS_PASSWORD: "{{ admin_password }}"
        OS_TENANT_NAME: admin
        OS_AUTH_URL: "{{ keystone_endpoint }}"

  tasks:
    - name: wait for keystone
      wait_for: host="{{ keystone_host }}" port=35357

    - name: wait for glance
      wait_for: host="{{ glance_host }}" port=9292

    - name: wait for nova-controller
      wait_for: host="{{ nova_controller_host }}" port=8774

    - name: create admin tenant
      keystone_user:
        tenant: admin
        tenant_description: Admin Tenant
        token: "{{ keystone_password }}"
        endpoint: "{{ keystone_endpoint }}"

    - name: create admin user
      keystone_user:
        user: "{{ admin_username}}"
        password: "{{ admin_password }}"
        tenant: admin
        token: "{{ keystone_password }}"
        endpoint: "{{ keystone_endpoint }}"

    - name: assign admin roles
      keystone_user:
        user: "{{ admin_username }}"
        tenant: admin
        role: "{{ item }}"
        token: "{{ keystone_password }}"
        endpoint: "{{ keystone_endpoint }}"
      with_items:
        - _member_
        - admin

    - name: create private network (demo-net)
      command:
          /usr/bin/nova network-create demo-net
            --fixed-range-v4 {{ fixed_range }}
            --bridge-interface br100
            --multi-host T
      ignore_errors: yes
      environment: openrc

    - name: set default security groups
      command: /usr/bin/nova secgroup-add-rule default {{ item }}
      ignore_errors: yes
      environment: openrc
      with_items:
        - icmp -1 -1 0.0.0.0/0 # PING
        - tcp 22 22 0.0.0.0/0  # SSH

    - name: add am admin-key key-pair
      nova_keypair:
        name: admin-key
        public_key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
        login_username: "{{ admin_username }}"
        login_password: "{{ admin_password }}"
        login_tenant_name: admin
        auth_url: "{{ keystone_endpoint }}"

    - name: add m1.micro flavor
      command: /usr/bin/nova flavor-create m1.micro 84 256 0 1
      ignore_errors: yes
      environment: openrc

    - name: add cirros
      glance_image:
        name: cirros-0.3.2-x86_64
        container_format: bare
        disk_format: qcow2
        copy_from: http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img
        login_username: "{{ admin_username }}"
        login_password: "{{ admin_password }}"
        login_tenant_name: admin
        auth_url: "{{ keystone_endpoint }}"
