- name: copy images sources
  synchronize: src=images/ dest={{ images_dir }}

- name: build images
  docker_image:
    name: "{{ item }}"
    path: "{{ images_dir }}/{{ item }}"
    state: build
  with_items: ambari_source_images  

- name: mark images to be pushed into local repository
  command: "docker tag -f {{ item }} datalyse-master:5000/{{ item }}"
  with_items: ambari_source_images

- name: push images into local repository
  command: "docker push datalyse-master:5000/{{ item }}"
  with_items: ambari_source_images