- name: start docker repository
  docker:
    image: registry
    name: registry
    hostname: registry
    ports: 5000:5000
    volumes: "/registry:/registry"
    env:
      SETTINGS_FLAVOR: local
      STORAGE_PATH: /registry
      DISABLE_TOKEN_AUTH: true
      STANDALONE: true