- name: install weave
  get_url: 
    url: https://github.com/zettio/weave/releases/download/latest_release/weave 
    dest: "{{ weave_bin }}"
    mode: 0755

- docker_facts: name=weave

- name: start weave
  command: "{{ weave_bin }} launch {{ weave_peer }}"
  when: docker_containers["weave"] is not defined or not docker_containers["weave"].docker_state.Running

- docker_facts: name=weavedns

- name: start weave-dns
  command: "{{ weave_bin }} launch-dns {{ weave_dns_cidr }}"
  when: docker_containers["weavedns"] is not defined or not docker_containers["weavedns"].docker_state.Running
