# ------------------------------------------------------------------------------
# NODES CONFIGURATION
# ------------------------------------------------------------------------------

NODES = [
  {:name => "control",  :ip => "192.168.42.11", :memory => 4096, :cpus => 4},
  {:name => "compute1", :ip => "192.168.42.12", :memory => 2048, :cpus => 2},
  {:name => "compute2", :ip => "192.168.42.13", :memory => 2048, :cpus => 2}
]

# ------------------------------------------------------------------------------
# VAGRANT SETUP
# ------------------------------------------------------------------------------

PIP_CONF_SH = <<SCRIPT
[ -d .pip ] || mkdir .pip
echo "[global]" > .pip/pip.conf
echo "download_cache = /var/cache/pip" >> .pip/pip.conf
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # setup cache
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    # setup PIP cache
    config.cache.enable :generic, { "pip" => { :cache_dir => "/var/cache/pip" } }
    config.vm.provision :shell, inline: PIP_CONF_SH
  else
    print "vagrant-cachier plugin has not been found."
    print "You can install it by `vagrant plugin install vagrant-cachier`"
  end

  config.vm.box = "precise64-cloud-image"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

  NODES.each do |node_config|
    config.vm.define node_config[:name] do |node|

      node.vm.hostname = node_config[:name]

      ## customize VM - networking
      # eth0: NAT network - is created by default by Vagrant
      # eth1: host-only network - to access the VM using its IP address
      node.vm.network :private_network, ip: node_config[:ip]
      
      ## customize VM - resources
      node.vm.provider :virtualbox do |vb|
        vb.memory = node_config[:memory]
        vb.cpus = node_config[:cpus]
      end
    end
  end
end
