- name: install apt-transport-https to let APT deal with https
  apt: name=apt-transport-https

- name: add docker repository key server
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add docker repository
  apt_repository: 
    repo: deb https://get.docker.com/ubuntu docker main
    state: present

- name: install docker
  apt: 
    name: lxc-docker
    force: yes

# alternative to docker deb, but even docker-machine uses deb
# - name: install latest docker
#   sudo: yes
#   shell: curl -sSL https://get.docker.com/ubuntu/ | sh -x
#   args:
#     creates: /usr/bin/docker

- name: configure docker
  lineinfile:
    dest: /etc/default/docker
    regexp: "^[#]?DOCKER_OPTS="
    line: DOCKER_OPTS="-D -H tcp://0.0.0.0:2375 -H unix:// --insecure-registry datalyse-master:5000"
    state: present
  notify:
    - restart docker

- meta: flush_handlers

- name: ensure docker is running
  service: name=docker state=running

- name: wait for docker
  wait_for: port=2375

- name: add local ssh user to docker group
  user: name={{ ansible_ssh_user }} groups=docker append=yes

- name: install docker-py
  pip: name=docker-py  